services:
  - type: web
    name: dsa-editor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
